-- הוספות (2026-08-17, בקשת עמנואל) — רק הוספות, לא נוגע בקיים:
--   1) מעקב קריאה: קטגוריות ניתנות-לעריכה + הערכות (ציון 1-10 לכל קטגוריה) לכל תלמיד.
--   2) אישור לימודים: הגדרות מוסד (חותמת/בלנק/מיקום) להדפסה.
-- אידמפוטנטי.

-- ══════════ 1) מעקב קריאה ══════════
create table if not exists public.reading_categories (
  id bigint generated by default as identity primary key,
  name text not null,
  sort_order int not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now()
);
-- זריעת 5 קטגוריות התחלתיות (רק אם ריק) — ניתנות לעריכה במסך ההגדרות
insert into public.reading_categories(name, sort_order)
  select v.n, v.o from (values ('שטף',1),('דיוק',2),('ניקוד',3),('הבנה',4),('מהירות',5)) as v(n,o)
  where not exists (select 1 from public.reading_categories);

create table if not exists public.reading_assessments (
  id bigint generated by default as identity primary key,
  student_id bigint not null references public.students(id) on delete cascade,
  assessed_on date not null default current_date,
  scores jsonb not null default '{}'::jsonb,   -- {"<category_id>": 1..10}
  note text,
  created_by uuid default auth.uid() references public.profiles(id),
  created_at timestamptz not null default now()
);
create index if not exists reading_assessments_student_idx on public.reading_assessments(student_id);

alter table public.reading_categories enable row level security;
alter table public.reading_assessments enable row level security;

-- קטגוריות: כל צוות קורא; רק מנהל עורך
drop policy if exists rcat_read on public.reading_categories;
create policy rcat_read on public.reading_categories for select to authenticated using ( public.is_staff() );
drop policy if exists rcat_admin on public.reading_categories;
create policy rcat_admin on public.reading_categories for all to authenticated
  using ( public.is_admin() ) with check ( public.is_admin() );

-- הערכות: מודל עמנואל — דיווח על כולם; צפייה רק לכיתה שלך (+ מה שאתה הזנת)
drop policy if exists rasm_ins on public.reading_assessments;
create policy rasm_ins on public.reading_assessments for insert to authenticated
  with check ( public.is_staff() );
drop policy if exists rasm_read on public.reading_assessments;
create policy rasm_read on public.reading_assessments for select to authenticated
  using ( public.is_admin() or created_by = auth.uid() or public.can_read_student(student_id) );
drop policy if exists rasm_upd on public.reading_assessments;
create policy rasm_upd on public.reading_assessments for update to authenticated
  using ( public.is_admin() or created_by = auth.uid() )
  with check ( public.is_admin() or created_by = auth.uid() );
drop policy if exists rasm_del on public.reading_assessments;
create policy rasm_del on public.reading_assessments for delete to authenticated
  using ( public.is_admin() or created_by = auth.uid() );

-- ══════════ 2) הגדרות מוסד לאישור לימודים ══════════
create table if not exists public.institution_settings (
  id int primary key default 1,
  stamp_data text,          -- data URI (base64) של חותמת
  letterhead_data text,     -- data URI (base64) של בלנק/רקע
  stamp_x int not null default 72,   -- מיקום חותמת ב-% (מרכז)
  stamp_y int not null default 80,
  stamp_size int not null default 130, -- רוחב חותמת בפיקסלים
  cert_title text not null default 'אישור לימודים',
  updated_at timestamptz not null default now(),
  constraint institution_single_row check (id = 1)
);
insert into public.institution_settings(id) values (1) on conflict (id) do nothing;

alter table public.institution_settings enable row level security;
-- כל צוות קורא (צריך לרנדר אישור); רק מנהל מעדכן (חותמת/בלנק)
drop policy if exists inst_read on public.institution_settings;
create policy inst_read on public.institution_settings for select to authenticated using ( public.is_staff() );
drop policy if exists inst_admin on public.institution_settings;
create policy inst_admin on public.institution_settings for all to authenticated
  using ( public.is_admin() ) with check ( public.is_admin() );
